### ISSUE TITLE
JSON Exception on Coin Detail - getCoinById

### ISSUE THREAD

**Issue by pabloim1** [DrewCarlson/CoinGecko-Kotlin#14]
Tested with token: holotoken (https://api.coingecko.com/api/v3/coins/holotoken)

Unexpected JSON token at offset 73165: Failed to parse 'double'
JSON input: .....ue,"whitelist_available":true,"pre_sale_available":null,"pre.....

IcoData Fields: 'whitelist_available' and 'pre_sale_available' should be Boolean? instead of Double?

I think those are the only two. Thanks!

**Comment by DrewCarlson** [comment]
Thanks, `0.1.6` will be available shortly.
