### ISSUE TITLE
CoinGeckoClient() constructor is a thread leaker

### ISSUE THREAD

**Issue by bartvanheukelom** [DrewCarlson/CoinGecko-Kotlin#162]
The no-arg CoinGeckoClient constructor creates a new HttpClient but never closes it. This is not just to be pedantic, it causes problems in reality. The utility function it uses to create the HttpClient makes it with the first engine found by ServiceLoader, which in my case is CIO. A CIOEngine starts a dispatcher with some threads, and these are never stopped, leading to a thread leak (as seen by a huge number of "ktor-cio-dispatcher-worker-N" threads) and an inevitable crash.

I would suggest making CoinGeckoClient implement AutoCloseable and closing the automatically constructed HttpClient in its close method (but not an externally provided HttpClient). If that's not possible I'd suggest deprecating the no-arg constructor or adding a big fat warning to its documentation.

**Comment by DrewCarlson** [comment]
Fixed in [v1.0.0-rc01](https://github.com/DrewCarlson/CoinGecko-Kotlin/releases/tag/v1.0.0-rc01)

**Comment by bartvanheukelom** [comment]
Appreciate the fast fix. Shame there isn't a stable closable interface, but at least that sounds like they're working on it?

**Comment by DrewCarlson** [comment]
Looks like it will be stable in Kotlin 2.0: https://youtrack.jetbrains.com/issue/KT-55777/Unresolved-kotlin.AutoCloseable-in-JVM#focus=Comments-27-7285243.0-0
