### ISSUE TITLE
Ktor 2.0.0 support

### ISSUE THREAD

**Issue by Queatz** [DrewCarlson/CoinGecko-Kotlin#35]
Seems like there are a few breaking changes in the HttpClient initialization which prevents me from upgrading my application to Ktor 2.0.0. Would it be possible to have a branch that uses Ktor 2?

**Comment by DrewCarlson** [comment]
[v0.4.0-beta01](https://github.com/DrewCarlson/CoinGecko-Kotlin/releases/tag/v0.4.0-beta01) will be available shortly, alternatively snapshots are available as 0.4.1-SNAPSHOT.

I'll leave this open in case others have the same question.

**Comment by DrewCarlson** [comment]
[v0.4.0](https://github.com/DrewCarlson/CoinGecko-Kotlin/releases/tag/v0.4.0) is available and updates to the final Ktor 2 release.
