### ISSUE TITLE
Json exception when trying to obtain list of CoinMarkets

### ISSUE THREAD

**Issue by pabloim1** [DrewCarlson/CoinGecko-Kotlin#5]
When trying to use method getCoinMarkets, the response is always:
Unexpected JSON token at offset 156: Failed to parse 'long'.
 JSON input: .....3579","current_price":11864.4,"market_cap":218935913104,"mar.....

**Comment by DrewCarlson** [comment]
Thanks for the report!

The current price field needs to be changed to a Double, I will update shortly.

https://github.com/DrewCarlson/CoinGecko-Kotlin/blob/d3bf5cb0ae1a524c014d759ae36fbb26745d322f/src/commonMain/kotlin/drewcarlson/coingecko/models/coins/CoinMarkets.kt#L18-L19

**Comment by DrewCarlson** [comment]
I've resolved the `CoinMarkets` serialization errors in version 0.1.2 with https://github.com/DrewCarlson/CoinGecko-Kotlin/commit/195ca05044ee13e4c63a7a702dd303e2b7c7847b.

**Comment by pabloim1** [comment]
Same issue with marketCapChange24h
Unexpected JSON token at offset 1075: Failed to parse 'long'.
 JSON input: .....ange_24h":-16411987808.987793,"market_cap_change_percentage_.....
Response example:
"market_cap_change_24h": -339302505.56848145,

And i think that for some coins, totalVolume will also be a double.
No sure about field marketCap.

**Comment by DrewCarlson** [comment]
OK, thanks for reporting again.  I only used Bitcoin in the test, though I see more should have been added.  Will do a more thorough check and get back to you.

**Comment by DrewCarlson** [comment]
Version 0.1.3 should be available shortly.  Let me know if any other endpoints give you trouble.

**Comment by pabloim1** [comment]
Thank you very much for the quick response and fix!!

**Comment by pabloim1** [comment]
Sorry, just tested, new issue
Unexpected JSON token at offset 60872: Expected string or non-null literal.
 JSON input: ....._volume":133562280,"high_24h":null,"low_24h":null,"price_cha.....

I guess high24 and low24 can be null. Probably the same with most fields.

**Comment by DrewCarlson** [comment]
That specific error is considered in https://github.com/DrewCarlson/CoinGecko-Kotlin/issues/1, there is a fix available that I will apply.

Can I ask if you are only using the JVM/Android artifacts?

**Comment by pabloim1** [comment]
Yes, I'm only using the JVM/Android artifact.

**Comment by DrewCarlson** [comment]
Can you try version 0.1.4-1.4.0-rc and see if that resolves the nullability error?

**Comment by pabloim1** [comment]
Just tested. It does solved the nullability error. Now I can fetch the first 100 coins without any errors.
