### ISSUE TITLE
Get Exchanges method not working

### ISSUE THREAD

**Issue by hackbyte07** [DrewCarlson/CoinGecko-Kotlin#80]
W/System.err: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the array '[', but had 'EOF' instead at path: $
W/System.err: JSON input: .....,"total":436,"perPage":100,"nextPage":2,"previousPage":null}

**Comment by DrewCarlson** [comment]
Fixed in [`v1.0.0-beta02`](https://github.com/DrewCarlson/CoinGecko-Kotlin/releases/tag/v1.0.0-beta02), it now returns a model with the list of exchanges and paging data.
